### ISSUE TITLE
pratt parser panics on invalid input

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#562]
Copied from https://github.com/0xalpharush/slang-fuzz/issues/1

```solidity
contract test {

	function intMinA() public pure returns (bool) {

		int8 int8_min = type(int8).min;
		require(int8_min == -2*;
  0   n == -2**127);

		return true;
	}

	function intMinC() public pure returreturn trb3
```

```log
thread '<unnamed>' panicked at 'removal index (is 2) should be < len (is 2)', /Users/alpharush/.cargo/git/checkouts/slang-30d565f6b9959ce1/c542db9/crates/solidity/outputs/cargo/crate/src/legacy/generated/parser_helpers.rs:277:37
```

**Comment by 0xalpharush** [comment]
Similar but distinct crash
```
contract test {
    function run(uint x1, uint x2, uint x3) public returns(uint y) {
        uint8 a = 0x1; uint8 b = 0x10; uint16 c = 0x100;
        y = a + b/+ c + x1 + x2 + x3;
        y += b + x2;
    }
}
// ----
// run(uint256,uint256,uint256): 0x1000, 0x10000, 0x100000 -> 0x121121

```
```
thread '<unnamed>' panicked at 'removal index (is 4) should be < len (is 4)', /Users/alpharush/.cargo/git/checkouts/slang-30d565f6b9959ce1/c542db9/crates/solidity/outputs/cargo/crate/src/legacy/generated/parser_helpers.rs:277:37
```
